import { verificarMotor } from "./verificar-motor";
import { verificarProvedor } from "./verificar-provedor";
import { verificarSkills } from "./verificar-skills";
import { verificarDesfazer } from "./verificar-desfazer";
import { verificarRegras } from "./verificar-regras";
import { verificarCusto } from "./verificar-custo";
import { verificarRotinas } from "./verificar-rotinas";
import { verificarCambio, verificarSugestoes } from "./verificar-sugestoes";
import { verificarFluxosModelo } from "./verificar-fluxos";
import { verificarAvaliarFluxo, verificarProcessoDaArvore } from "./verificar-avaliar";
import { verificarInferirFluxo } from "./verificar-inferir";
import { verificarEstudio } from "./verificar-estudio";
import { resumo } from "./util";

await verificarMotor();
await verificarProvedor();
await verificarSkills();
verificarDesfazer();
verificarRegras();
verificarCusto();
verificarRotinas();
verificarSugestoes();
verificarCambio();
verificarFluxosModelo();
verificarAvaliarFluxo();
verificarProcessoDaArvore();
await verificarInferirFluxo();
verificarEstudio();
resumo();
